repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000'] # 1MB limit
      - id: check-yaml
        args: ['--unsafe'] # Allow unsafe YAML for configs
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf'] # Force LF line endings
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  # Code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [javascript, json, markdown, yaml]
        args: ['--write', '--ignore-unknown']
        exclude: '^(.git/|node_modules/|dist/|coverage/)'

  # TypeScript and testing
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        entry: npx tsc --noEmit
        language: system
        files: \.(ts)$
        pass_filenames: false
        always_run: true

      - id: unit-tests
        name: Unit Tests
        entry: npm run test
        language: system
        files: \.(ts)$
        pass_filenames: false
        always_run: true

      - id: lint-check
        name: ESLint Check
        entry: npm run lint:check
        language: system
        files: \.(ts|js)$
        pass_filenames: false
        always_run: true

      - id: format-check
        name: Format Check
        entry: npm run format:check
        language: system
        files: \.(ts|js|json|md|yaml)$
        pass_filenames: false
        always_run: true
