repos:
  # Basic file checks (Windows-compatible)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: ^(dist/|node_modules/|coverage/|\.vite/|\.claude/|.*\.map$|.*\.min\.js$)

  # Local hooks for our specific tools
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint
        language: system
        files: ^src/.*\.ts$
        args: [--fix]
        pass_filenames: false
        always_run: true

      - id: type-check
        name: type-check
        entry: npx tsc --noEmit
        language: system
        files: ^src/.*\.ts$
        pass_filenames: false
        always_run: true

      - id: unit-tests
        name: unit-tests
        entry: npm test
        language: system
        files: ^src/.*\.ts$
        pass_filenames: false
        always_run: true
