services:
  tappmcp-http:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CONTEXT7_API_KEY=ctx7sk-45825e15-2f53-459e-8688-8c14b0604d02
      - CONTEXT7_USE_HTTP_ONLY=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
